In [4]:
a = 1; print(type(a))

<class 'int'>


a = 1 : 1이라는 정수값을 변수 a에 지정(assign)한다.  
type() 함수 : 인자(함수 뒤 괄호에 들어가는 것)로 들어가는 값의 자료형을 반환해주는 파이썬 내장함수  
print() 함수 : 인자를 화면출력하는 파이썬 내장함수  
1은 정수이므로, 1의 자료형은 integer(정수)를 의미하는 int이다.

In [5]:
a = 1; a = float(a); print(type(a))

<class 'float'>


세미클론은 여러 줄의 코드를 하나의 줄에서 실행할 수 있도록 해준다.  
따라서의 위의 코드는 a = 1, a = float(a), 그리고 print(type(a))라는 세 개의 코드를 앞에서부터 순차적으로 실행하게 되는 것이다.  
먼저, 1을 a에 지정한다.  
float() 함수는 인자의 자료형을 float(실수형)으로 변환한 값을 반환한다. a = float(a)를 실행하면, 1이라는 값을 가지고 있던 변수 a에 1.0라는 실수형으로 바뀐 새로운 값을 지정하게 된다. 즉, 변수 a는 더이상 1이 아니라 1.0이라는 값을 갖게 되는 것이다.

In [6]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


1.2을 변수 a에 지정한 후, a의 값을 정수(int)로 변환한 값을 다시 변수에 새로 지정한다. 그리고 a의 자료형(type)을 화면출력(print)한다.

In [7]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


인용부호('' 또는 "")로 양끝이 묶여있는 값을 '문자열'이라고 부른다.  
a = '123' : '123'이라는 문자열 값을 변수 a에 지정한다.  
print(type(a)) : a의 자료형(type)을 화면출력하면 문자열(string)을 나타내는 str이 나타난다.  

문자열은 시퀀스(sequence) 자료형이다. 시퀀스 자료형의 예로는 문자열, 리스트, 튜플, 딕셔너리 등이 있다. 시퀀스 자료형의 특징은 인덱싱(indexing)를 통해서 시퀀스를 이루는 원소 하나하나에 접근할 수 있다는 것이다. 인덱스는 값 또는 변수명 옆의 square bracket([])내에 정수이다. 예를 들어, 위 코드에서 a[1]은 a의 1번째 원소, 즉, 1번째 문자(character)인 2다. 여기서 주의할 점은 인용부호로 묶여진 숫자(123)은 정수형이 아니라 어디까지나 문자(character)에 불과하다는 것이다. 또한 파이썬의 인덱스는 1이 아니라 0에서부터 시작한다.  

print(a[1]) : a[1]은 '2'이므로 문자열이다. 문자열은 인용부호('')로 묶여있으나, 화면출력(print)시에는 인용부호가 빠져서 출력된다.

In [8]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


a = '123' : 문자열 '123'을 변수 a에 지정한다.  
a = list(a) : 변수 a의 자료형을 리스트(list)로 변환하여 그 값을 a에 지정한다. 문자열을 리스트로 변환하면, 문자열내의 문자 한개마다 쪼개져 리스트의 원소 하나가 된다. 리스트는 원소들이 쉼표(,)로 구분되며, 양끝에는 꺾쇠괄호([])로 묶여있다. 이 경우, 문자열 '123'을 list() 함수를 통해 리스트로 변환하면, ['1', '2', '3']가 된다.  
리스트도 문자열과 마찬가지로 시퀀스 자료형이다. 따라서 인덱싱을 통해 리스트의 원소에 접근할 수 있다. a[2]는 리스트의 2번째 원소이므로 '3'이다. 그것을 화면출력(print)하게 되면, 인용부호가 빠진 3이 화면출력된다. 

In [9]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


리스트의 원소는 숫자, 문자열 뿐만 아니라 리스트도 될 수 있다(cf.그밖에도 다양한 자료형의 값이 리스트의 원소가 될 수 있다.). a = [1,'2', [3, '4']] 처럼 리스트 내에 리스트가 있는 경우, 이를 '중첩(nested) 리스트'라고 부른다.  
중첩 리스트의 자료형도 앞전과 같이 리스트다.  
리스트의 원소로 있는 리스트에 접근하기 위해서는 앞전과 동일한 방식으로 인덱싱을 사용하면 된다.  
a[2]는 2번째 원소인 [3,'4']이다. 화면출력시 인용부호가 빠지는 문자열과 달리, 리스트는 꺾쇠부호가 그대로 출력된다.

In [10]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


소괄호()로 묶여져 있는 시퀀스 자료형을 '튜플(tuple)'이라고 부른다.  
튜플은 리스트와 비슷하나 결정적인 차이점은 '변경불가능'하다는 것이다. ex) a[0] = 2 하면 오류가 발생한다.

In [11]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


{"a": "apple", "b": "orange", "c": 2014} 같은 자료형을 '사전'(dictionary)라고 한다.
사전은 중괄호{}로 묶여있으며, 원소는 키(key):값(value)의 형태로 이루어져있다. 이때 주의할 점은 사전의 key는 반드시 변경불가능한 자료형이어야한다는 것이다. 사전 자체는 변경가능한 자료형이다.  

리스트와 튜플은 원소들 간의 순서가 있어 인덱싱을 통해 원소에 접근하는 반면에,  
사전은 원소들 간의 순서가 없어 키(key)를 통해 값(value)을 찾는다. 사전명[키] 는 그 키에 대응하는 값을 나타낸다. 이 경우 a["a"]는 'apple'이다.

In [12]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

리스트의 원소가 튜플인 경우이다. 가장 바깥쪽에 있는 기호가 대괄호[]이므로 전체 a의 자료형은 리스트다. 

In [13]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


import - 외부라이브러리를 다운받고 메모리 위에 올려놓는다.  
라이브러리는 아나콘다 디렉토리(폴더)에 폴더의 형태로 들어가있다.  
import numpy는 numpy라는 폴더(디렉토리)를 메모리 상으로 가져온다.  
import numpy as np는 numpy라는 라이브러리를 np라는 명칭(호칭)으로 가져온다는 뜻이다.  
np.array()는 numpy 라이브러리 내에 있는 array함수를 사용하겠다는 것인데, np.array() 함수는 인자의 값을 배열(array)로 변환해준다.

In [14]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


엄밀히 말하자면, 배열은 행렬과 다른 자료형이다.
행렬의 경우, 2x3와 2x3의 행렬끼리 곱할 수 없지만, 배열은 가능하다.

In [15]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


np.matrix는 행렬로 변환해주는 함수.  
행렬로 바꿨을때 2x3, 2x3 행렬끼리 곱해지지 않는다.  
객체 지향: 어떤 변수는 어떤 함수들과 패키지로 묶어버리는 것.  
객체 지향을 통해 만들어진 것을 'class'라고 함.

In [16]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

행렬로 바뀐 c끼리 곱하면 ValueError가 발생한다. 

In [17]:
c*c.T

matrix([[14, 19],
        [19, 73]])

np.matrix.T는 해당 행렬의 transpose(전치행렬)을 반환해준다. 이때, T 메소드는 값을 반환할 뿐 T앞의 변수의 값을 변경하지 못한다. 예를 들어, c.T를 한다고 해서 변수 c 자체는 바뀌지 않는다는 것이다.